GN-4323: Make document public
lblod/app-reglementaire-bijlage pull request #55
Opened 2023-06-22 08:01 UTC by dkozickis

### Overview

Makes `DocumentContainer` and `EditorDocument` publicly accessible to enable querying for snippet content, which is stored in `EditorDocument`.

#### Connected issues and PRs:

Insert snippet JIRA - https://binnenland.atlassian.net/browse/GN-4323
Pending PR in plugins - https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/165

### Setup

Usual launch with docker, make sure the migration runs, running the SPARQL query publicly

```sparql
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX pav: <http://purl.org/pav/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
SELECT (COUNT(?snippetDocument) AS ?count)
WHERE {
    ?snippetList a ext:SnippetList ;
  		ext:hasSnippet/pav:hasCurrentVersion ?snippetDocument .
}
```

Should now give you the correct count

### Challenges/uncertainties

My first time writing a SPARQL migration, please check it thoroughly 😅 it did work locally...

2023-06-23 13:02 UTC, abeforgit requested changes
as I expected, this breaks the creation/edit of documents in the RB frontend

EDIT: it also doesn't fix the problems with the snippet insertion afaict
how I tested that :
- setup plugin dummy app
- setup this backend
- edit the code to point to `http://localhost:<identifier port>/sparql`
- try to load the snippets

2023-06-28 13:49 UTC, abeforgit commented
Unrelated to this specific pr, but i'm not gonna go hunt for the pr that introduced it
in the translatation files, the `fragment-plugin.modal.alert.error-intro` key references the Vlaamse Codex (Flemish Codex) which has nothing to do with this plugin.

2023-06-30 14:56 UTC, abeforgit commented
wow I didn't realize I posted that comment in the backend PR :joy: sorry about that, but the translation is good

2023-06-30 20:08 UTC, abeforgit reviewed
I talked with niels about this and we're having some concerns.
Mainly, this makes all documents public, which we actually don't want. That's on me, I thought we did, but I forgot about this draft/publish flow we have for the regulations. Documents are actually private until ready, and we would break that with this. 

An option could be to use a subclass of DocumentContainer for snippets, and then make only that subclass public. But we need to confirm with Aad whether that will work as expected with mu-auth

2023-07-13 10:45 UTC, elpoelma commented
@dkozickis I suppose we can close this one off?

2023-07-13 11:05 UTC, closed without merging