GN-4323: Public snippet
lblod/app-reglementaire-bijlage pull request #59
Opened 2023-07-12 06:24 UTC by dkozickis

### Overview

Copies required `SnippetList` information to public graph, to enable querying from unauthorised frontends.

#### Connected issues and PRs:

https://binnenland.atlassian.net/browse/GN-4323

### Setup

1. Checkout https://github.com/lblod/reglement-publish-service/pull/10 for `reglement-publish-service/` repository
2. Checkout https://github.com/lblod/app-reglementaire-bijlage/pull/59 for `app-reglementaire-bijlage`
3. In the `app-reglementaire-bijlage` repo add a `docker-compose.extra.yml` file with content of
    ```docker
    version: "3.4"
    services:
      publisher:
        image: mu-javascript-template:latest
        links:
          - database:database
        environment:
          NODE_ENV: "development"
        volumes:
          - ./data/files/:/share/
          - /absolute/path/to/reglement-publish-service/:/app/
        restart: always
    ```
    note that `/absolute/path/to/reglement-publish-service/` should be an absolute path to where you have `frontend-reglementaire-bijlage` checked out.
4. In `app-reglementaire-bijlage` run

    ```sh
    docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.extra.yml up
    ```
    to bring the modified `app-reglementaire-bijlage` with modified `reglement-publish-service` up
5. Checkout https://github.com/lblod/frontend-reglementaire-bijlage/pull/136 for `frontend-reglementaire-bijlage`
6. Inside `frontend-reglementaire-bijlage` do `npm i` and server it with `ember s --proxy http://localhost`
7. Checkout https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/207 for `ember-rdfa-editor-lblod-plugins`
8. Inside `ember-rdfa-editor-lblod-plugins` do `npm i` and server it with `PORT=4300 npm run start`

### How to test/reproduce

Modified `frontend-reglementaire-bijlage` should be running on localhost on port 4200.
Modified `ember-rdfa-editor-lblod-plugins` should be running on localhost on port 4300.

* Go to http://localhost:4200/mock-login to login into RB frontend
* Create a Snippet List, and create a snippet within that list. Observe that all is working, snippet is saved and there are no console/network errors.
* Go to http://localhost:4300/regulatory-statement-sample (plugin test frontend)
* In the right sidebar click "Insert" and click "Insert snippet". Observe that snippets are visible and it is possible to insert them.
* Go back to RB frontend and update a snippet or create a new one
* Go back to Plugin frontend and observe that snippets are updated/created. It may take some time until SPARQL cache gets thrown and starts returning updates though.

2023-07-14 07:40 UTC, elpoelma reviewed
Looks good to me overall, will update this review once I tested everything. 
On the change in `goverment.json`, was the prefix used just plain wrong/undefined there?

2023-07-14 19:25 UTC, abeforgit requested changes

2023-07-14 19:25 UTC, abeforgit commented on config/resources/domain.json
> +      "relationships": {
this doesn't have a link to the previous version
I think its quite important to have that

2023-07-24 07:48 UTC, elpoelma commented
@dkozickis once the reglement-publish-service and editor-plugins are released, can you update this PR. Then we can merge it too.

2023-07-24 10:40 UTC, merged